# Generated by Django 5.0.6 on 2024-12-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0004_company_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_staff',
            name='socket_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
