# Generated by Django 5.1.3 on 2024-12-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0006_company_type_user_file_safe_company_staff_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_staff",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
