# Generated by Django 5.0.6 on 2024-12-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0008_company_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_staff',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quan_ly_nhan_luc.company_account'),
        ),
    ]
