# Generated by Django 5.0.6 on 2024-12-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0009_alter_company_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='company_account',
        ),
    ]
