# Generated by Django 5.1.3 on 2024-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0012_company_account_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company_staff_profile",
            old_name="socket_id",
            new_name="birthday",
        ),
        migrations.RemoveField(
            model_name="company_staff_profile",
            name="isOnline",
        ),
        migrations.RemoveField(
            model_name="company_staff_profile",
            name="isValidate",
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="facebook",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="instagram",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="phone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="tiktok",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="zalo_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="zalo_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
