# Generated by Django 5.1.3 on 2024-12-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0014_company_staff_profile_sologan"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_staff_profile",
            name="bank",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="company_staff_profile",
            name="bank_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="company_staff_profile",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company_staff_profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
