# Generated by Django 5.1.3 on 2024-12-11 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0018_company_operator_chu_taikhoan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operator_history",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="operator_history",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="operator_history",
            name="vendor",
        ),
        migrations.DeleteModel(
            name="company_operator",
        ),
        migrations.DeleteModel(
            name="operator_history",
        ),
    ]
