# Generated by Django 5.1.3 on 2024-12-11 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0019_remove_operator_history_operator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="company_operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ma_nhanvien",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sdt", models.CharField(blank=True, max_length=15, null=True)),
                ("ho_ten", models.CharField(blank=True, max_length=200, null=True)),
                ("ten_goc", models.CharField(blank=True, max_length=200, null=True)),
                ("so_cccd", models.CharField(blank=True, max_length=200, null=True)),
                ("ngaysinh", models.DateField(blank=True, null=True)),
                ("diachi", models.TextField(blank=True, null=True)),
                (
                    "so_taikhoan",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "chu_taikhoan",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "ghichu_taikhoan",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ghichu", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quan_ly_nhan_luc.company",
                    ),
                ),
                (
                    "nguoituyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quan_ly_nhan_luc.company_staff",
                    ),
                ),
                (
                    "nhachinh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quan_ly_nhan_luc.company_supplier",
                    ),
                ),
                (
                    "nhacungcap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quan_ly_nhan_luc.company_vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="operator_history",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operator_histories",
                        to="quan_ly_nhan_luc.company_customer",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_histories",
                        to="quan_ly_nhan_luc.company_operator",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operator_histories",
                        to="quan_ly_nhan_luc.company_vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operator History",
                "verbose_name_plural": "Operator Histories",
                "ordering": ["-start_date"],
            },
        ),
    ]
