# Generated by Django 5.1.3 on 2024-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0020_company_operator_operator_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_customer",
            name="staffs",
            field=models.ManyToManyField(
                blank=True,
                related_name="customers",
                to="quan_ly_nhan_luc.company_staff",
            ),
        ),
    ]
