# Generated by Django 5.0.6 on 2024-12-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0022_company_customer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_supplier',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company_vendor',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
