# Generated by Django 5.0.6 on 2024-12-16 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0023_company_supplier_website_company_vendor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='wallpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpn_wallpaper', to='quan_ly_nhan_luc.image_safe'),
        ),
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpn_avatar', to='quan_ly_nhan_luc.image_safe'),
        ),
    ]
