# Generated by Django 5.1.3 on 2024-12-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0024_company_wallpaper_alter_company_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company",
                "verbose_name_plural": "Company",
            },
        ),
        migrations.AlterModelOptions(
            name="company_account",
            options={
                "verbose_name": "Company Accounts",
                "verbose_name_plural": "Company Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="company_customer",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Customers",
                "verbose_name_plural": "Company Customers",
            },
        ),
        migrations.AlterModelOptions(
            name="company_department",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Departments",
                "verbose_name_plural": "Company Departments",
            },
        ),
        migrations.AlterModelOptions(
            name="company_operator",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Operators",
                "verbose_name_plural": "Company Operators",
            },
        ),
        migrations.AlterModelOptions(
            name="company_possition",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Possitions",
                "verbose_name_plural": "Company Possitions",
            },
        ),
        migrations.AlterModelOptions(
            name="company_staff",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Staff",
                "verbose_name_plural": "Company Staff",
            },
        ),
        migrations.AlterModelOptions(
            name="company_staff_history",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Staff History",
                "verbose_name_plural": "Company Staff History",
            },
        ),
        migrations.AlterModelOptions(
            name="company_staff_history_action",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Staff Action Historys",
                "verbose_name_plural": "Company Staff Action Historys",
            },
        ),
        migrations.AlterModelOptions(
            name="company_staff_history_function",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Staff Action History Functions",
                "verbose_name_plural": "Company Staff Action History Functions",
            },
        ),
        migrations.AlterModelOptions(
            name="company_staff_profile",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Staff Profiles",
                "verbose_name_plural": "Company Staff Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="company_supplier",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Suppliers",
                "verbose_name_plural": "Company Suppliers",
            },
        ),
        migrations.AlterModelOptions(
            name="company_type",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Types",
                "verbose_name_plural": "Company Types",
            },
        ),
        migrations.AlterModelOptions(
            name="company_vendor",
            options={
                "ordering": ["-id"],
                "verbose_name": "Company Vendors",
                "verbose_name_plural": "Company Vendors",
            },
        ),
        migrations.AlterUniqueTogether(
            name="company_customer",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="company_operator",
            unique_together={("company", "ma_nhanvien")},
        ),
        migrations.AlterUniqueTogether(
            name="company_staff",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="company_supplier",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="company_vendor",
            unique_together={("company", "name")},
        ),
    ]
