# Generated by Django 5.1.3 on 2024-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0026_integrityerrorlog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integrityerrorlog",
            options={
                "ordering": ["-id"],
                "verbose_name": "API Errors",
                "verbose_name_plural": "API Errors",
            },
        ),
        migrations.AddField(
            model_name="integrityerrorlog",
            name="api_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="integrityerrorlog",
            name="models_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
