# Generated by Django 5.0.6 on 2024-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0026_company_facebook_company_instagram_company_tiktok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_operator',
            name='gioi_tinh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company_operator',
            name='quequan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
