# Generated by Django 5.1.3 on 2024-12-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0027_alter_integrityerrorlog_options_and_more"),
        ("quan_ly_nhan_luc", "0029_company_operator_nguoibaocao_and_more"),
    ]

    operations = []
