# Generated by Django 5.1.3 on 2024-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0030_merge_20241220_2106"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="taxCode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
