# Generated by Django 5.1.3 on 2024-12-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0031_company_taxcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_operator",
            name="congty_danglam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quan_ly_nhan_luc.company_customer",
            ),
        ),
    ]
