# Generated by Django 5.1.3 on 2024-12-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0032_company_operator_congty_danglam"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator_history",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operator_histories",
                to="quan_ly_nhan_luc.company_supplier",
            ),
        ),
    ]
