# Generated by Django 5.1.3 on 2024-12-22 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0033_operator_history_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator_history",
            name="ma_nhanvien",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="operator_history",
            name="noihopdong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_histories",
                to="quan_ly_nhan_luc.operator_history",
            ),
        ),
    ]
