# Generated by Django 5.1.3 on 2024-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0034_operator_history_ma_nhanvien_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operator_history",
            options={
                "ordering": ["-id"],
                "verbose_name": "Operator History",
                "verbose_name_plural": "Operator Histories",
            },
        ),
        migrations.AddField(
            model_name="operator_history",
            name="anh_cccd",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operator_history",
            name="so_cccd",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="company_operator",
            name="diachi",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="company_operator",
            name="ghichu",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="company_operator",
            name="quequan",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
