# Generated by Django 5.1.3 on 2024-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0035_alter_operator_history_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operator_history",
            old_name="anh_cccd",
            new_name="anh_cccd_back",
        ),
        migrations.AddField(
            model_name="company_operator",
            name="anh_cccd_back",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company_operator",
            name="anh_cccd_front",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="operator_history",
            name="anh_cccd_front",
            field=models.TextField(blank=True, null=True),
        ),
    ]
