# Generated by Django 5.0.6 on 2025-01-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0036_rename_anh_cccd_operator_history_anh_cccd_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_operator',
            old_name='anh_cccd_back',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='company_operator',
            old_name='anh_cccd_front',
            new_name='cccd_back',
        ),
        migrations.AddField(
            model_name='company_operator',
            name='cccd_front',
            field=models.TextField(blank=True, null=True),
        ),
    ]
