# Generated by Django 5.0.6 on 2025-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0037_rename_anh_cccd_back_company_operator_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhanQuyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('add_operator', 'Thêm người lao động'), ('view_operator', 'Xem người lạo động'), ('update_operator', 'Cập nhập người lạo động'), ('update_all_operator', 'Cập nhập người lạo động')],
            },
        ),
    ]
