# Generated by Django 5.0.6 on 2025-01-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0038_phanquyen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhanQuyen',
        ),
    ]
