# Generated by Django 5.0.6 on 2025-02-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0040_permission_companypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator_history',
            name='nguoituyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyHIS_nguoituyen', to='quan_ly_nhan_luc.company_staff'),
        ),
        migrations.AddField(
            model_name='operator_history',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
