# Generated by Django 5.0.6 on 2025-02-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0042_advancereasontype_advancetype_advancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_nhan_luc.company'),
        ),
        migrations.AddField(
            model_name='advancetype',
            name='need_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_requests', to='quan_ly_nhan_luc.company_staff'),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='requesttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_type', to='quan_ly_nhan_luc.advancetype'),
        ),
    ]
