# Generated by Django 5.0.6 on 2025-02-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0043_advancerequest_company_advancetype_need_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereasontype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_nhan_luc.company'),
        ),
        migrations.AddField(
            model_name='advancetype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quan_ly_nhan_luc.company'),
        ),
    ]
