# Generated by Django 5.0.6 on 2025-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0046_advancerequesthistory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancerequest',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
