# Generated by Django 5.0.6 on 2025-03-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0047_advancerequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
