# Generated by Django 5.1.3 on 2025-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0049_advancerequest_hinhthucthanhtoan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advancerequest",
            name="nguoiThuhuong",
            field=models.CharField(
                choices=[
                    ("other", "Người khác"),
                    ("opertor", "Người lao động"),
                    ("staff", "Người tuyển"),
                ],
                default="opertor",
                max_length=10,
            ),
        ),
    ]
