# Generated by Django 5.0.6 on 2025-03-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0050_alter_advancerequest_nguoithuhuong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa'), ('paid', 'Xong')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='retrieve_status',
            field=models.CharField(choices=[('not_retrieved', 'Chưa'), ('retrieved', 'Xong')], default='not_retrieved', max_length=15),
        ),
    ]
