# Generated by Django 5.0.6 on 2025-03-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0052_advancerequest_request_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancereasontype',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
