# Generated by Django 5.0.6 on 2025-03-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0053_advancereasontype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancereasontype',
            name='color',
        ),
        migrations.AddField(
            model_name='advancetype',
            name='color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=10, null=True),
        ),
    ]
