# Generated by Django 5.0.6 on 2025-03-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0054_remove_advancereasontype_color_advancetype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='payment_status',
            field=models.CharField(choices=[('not', 'Chưa'), ('done', 'Xong')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='retrieve_status',
            field=models.CharField(choices=[('not', 'Chưa'), ('done', 'Xong')], default='not_retrieved', max_length=15),
        ),
    ]
