# Generated by Django 5.0.6 on 2025-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quan_ly_nhan_luc', '0055_alter_advancerequest_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancerequest',
            name='payment_status',
            field=models.CharField(choices=[('not', 'Chưa'), ('done', 'Xong')], default='not', max_length=10),
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='retrieve_status',
            field=models.CharField(choices=[('not', 'Chưa'), ('done', 'Xong')], default='not', max_length=15),
        ),
    ]
