# Generated by Django 5.1.3 on 2025-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0056_alter_advancerequest_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_staff_profile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="advancerequest",
            name="nguoiThuhuong",
            field=models.CharField(
                choices=[
                    ("other", "Người khác"),
                    ("opertor", "Người lao động"),
                    ("staff", "Người tạo yêu cầu"),
                ],
                default="opertor",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="advancetype",
            name="color",
            field=models.CharField(
                blank=True, default="#999999", max_length=10, null=True
            ),
        ),
    ]
