# Generated by Django 5.1.3 on 2025-03-24 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0059_bangcong_check_in_bangcong_check_out_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "Xem"),
                            ("edit", "Sửa"),
                            ("delete", "Xóa"),
                            ("update", "Cập nhật"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_permissions",
                        to="quan_ly_nhan_luc.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Permission",
                "verbose_name_plural": "Sub Permissions",
                "ordering": ["permission", "permission_type"],
                "unique_together": {("permission", "permission_type")},
            },
        ),
    ]
