# Generated by Django 5.1.3 on 2025-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0060_subpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="fullname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
