# Generated by Django 5.1.3 on 2025-03-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0061_permission_fullname_alter_permission_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companypermission",
            options={
                "verbose_name": "Permission at Company",
                "verbose_name_plural": "Permissions at Company",
            },
        ),
        migrations.AlterModelOptions(
            name="subpermission",
            options={
                "ordering": ["permission", "permission_type"],
                "verbose_name": "Permissions Subs",
                "verbose_name_plural": "Permissions Subs",
            },
        ),
        migrations.AddField(
            model_name="companypermission",
            name="excluded_departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="excluded_permissions",
                to="quan_ly_nhan_luc.company_department",
            ),
        ),
        migrations.AddField(
            model_name="companypermission",
            name="sub_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="company_permissions",
                to="quan_ly_nhan_luc.subpermission",
            ),
        ),
        migrations.AlterField(
            model_name="companypermission",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_permissions",
                to="quan_ly_nhan_luc.company_staff",
            ),
        ),
        migrations.AlterField(
            model_name="companypermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_permissions",
                to="quan_ly_nhan_luc.permission",
            ),
        ),
    ]
