# Generated by Django 5.1.3 on 2025-03-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0062_alter_companypermission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subpermission",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("me", "Cá nhân"),
                    ("position", "Vị trí"),
                    ("department", "Phòng ban"),
                    ("all", "Tất cả"),
                ],
                default="me",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subpermission",
            name="permission_type",
            field=models.CharField(
                choices=[
                    ("view", "Xem"),
                    ("edit", "Sửa"),
                    ("delete", "Xóa"),
                    ("update", "Cập nhật"),
                    ("close", "Đóng"),
                    ("open", "Mở"),
                    ("approve", "Duyệt"),
                    ("reject", "Từ chối"),
                ],
                max_length=20,
            ),
        ),
    ]
