# Generated by Django 5.1.3 on 2025-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0063_subpermission_target_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subpermission",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
