# Generated by Django 5.1.3 on 2025-03-24 16:44

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    PermissionType = apps.get_model('quan_ly_nhan_luc', 'PermissionType')
    TargetType = apps.get_model('quan_ly_nhan_luc', 'TargetType')

    permission_types = [
        ('view', 'Xem'),
        ('edit', 'Sửa'),
        ('delete', 'Xóa'),
        ('update', 'Cập nhật'),
        ('close', 'Đóng'),
        ('open', 'Mở'),
        ('approve', 'Duyệt'),
        ('reject', 'Từ chối'),
    ]
    target_types = [
        ('me', 'Cá nhân'),
        ('position', 'Vị trí'),
        ('department', 'Phòng ban'),
        ('all', 'Tất cả'),
    ]

    for name, display_name in permission_types:
        PermissionType.objects.get_or_create(name=name, display_name=display_name)
    for name, display_name in target_types:
        TargetType.objects.get_or_create(name=name, display_name=display_name)
        
class Migration(migrations.Migration):

    dependencies = [
        ("quan_ly_nhan_luc", "0064_alter_subpermission_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Permission Type",
                "verbose_name_plural": "Permission Types",
            },
        ),
        migrations.CreateModel(
            name="TargetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("display_name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Target Type",
                "verbose_name_plural": "Target Types",
            },
        ),
        migrations.RemoveField(
            model_name="companypermission",
            name="sub_permissions",
        ),
        migrations.AddField(
            model_name="companypermission",
            name="permission_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="company_permissions",
                to="quan_ly_nhan_luc.permissiontype",
            ),
        ),
        migrations.AddField(
            model_name="companypermission",
            name="target_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="company_permissions",
                to="quan_ly_nhan_luc.targettype",
            ),
        ),
        migrations.DeleteModel(
            name="SubPermission",
        ),migrations.RunPython(load_initial_data)
    ]
