# Generated by Django 5.0.6 on 2024-09-16 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('filename', models.CharField(blank=True, max_length=150, null=True)),
                ('filesize', models.CharField(blank=True, max_length=150, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalo_id', models.CharField(max_length=50, unique=True)),
                ('zalo_name', models.CharField(blank=True, max_length=50, null=True)),
                ('zalo_avatar', models.CharField(blank=True, max_length=250, null=True)),
                ('zalo_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('huyen', models.CharField(blank=True, max_length=150, null=True)),
                ('tinh', models.CharField(blank=True, max_length=150, null=True)),
                ('long_pos', models.CharField(blank=True, max_length=50, null=True)),
                ('lat_pos', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_profiles', to='app.photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('wallpaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpaper_profiles', to='app.photos')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('jobs_title', models.CharField(blank=True, max_length=255, null=True)),
                ('working_day', models.IntegerField(default=0)),
                ('ngay_nghi', models.CharField(blank=True, max_length=255, null=True)),
                ('calamviec', models.CharField(blank=True, max_length=255, null=True)),
                ('finish_working_day', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_tangca', models.BooleanField(default=True)),
                ('checked_date', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_salaries', to='app.worksheet')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.IntegerField(blank=True, choices=[(0, 'Không phép'), (1, 'Có phép'), (2, 'Hưởng lương'), (3, 'Nghỉ ốm')], null=True)),
                ('bonus_salary', models.IntegerField(blank=True, null=True)),
                ('giobinhthuong', models.FloatField(blank=True, default=0, null=True)),
                ('giotangca', models.FloatField(blank=True, default=0, null=True)),
                ('heso', models.FloatField(blank=True, default=100, null=True)),
                ('work_date', models.DateField(default=django.utils.timezone.now)),
                ('is_working', models.BooleanField(default=True)),
                ('off_special', models.BooleanField(default=False)),
                ('off_rate', models.FloatField(blank=True, default=0, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('over_time', models.FloatField(blank=True, default=0, null=True)),
                ('late_time', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='app.worksheet')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
