# Generated by Django 5.0.6 on 2024-09-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photos_profile_worksheet_worksalary_workrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zalo_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
