# Generated by Django 5.0.2 on 2024-09-16 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_company_companydepartment_companysalaryrule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyemployee',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='bind_to',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='companysalarydetails',
            name='name',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='app_level',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('staff', 'staff'), ('normal', 'normal')], default='normal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='bank_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='bank_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CompanyEmployee_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CompanyEmployee_bind', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companyposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CompanySalaryFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_Overtime', models.BooleanField(default=True)),
                ('default_value', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='companysalarydetails',
            name='salaryFormat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companysalaryformat'),
        ),
        migrations.CreateModel(
            name='CompanySalaryFormatConditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDay', models.IntegerField(default=0)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salaryFormat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companysalaryformat')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWokingday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDay', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.FloatField(blank=True, default=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorkshift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('startTime', models.TimeField(default='08:00:00')),
                ('finishTime', models.TimeField(default='17:00:00')),
                ('rate', models.FloatField(blank=True, default=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workDay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companywokingday')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorkrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('startTime', models.TimeField(default='08:00:00')),
                ('finishTime', models.TimeField(default='17:00:00')),
                ('rate', models.FloatField(blank=True, default=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companyworkshift')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorkshiftFreetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('startTime', models.TimeField(default='10:00:00')),
                ('finishTime', models.TimeField(default='10:15:00')),
                ('isPay', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.companyworkshift')),
            ],
        ),
    ]
