# Generated by Django 5.0.6 on 2024-09-26 05:56

import app.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_first_name_companyemployee_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysalaryrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydepartment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companywokingday',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysalaryformat',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyposition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='personal_salary',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companyposition',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='companysalarydetails',
            name='salaryFormat',
        ),
        migrations.RemoveField(
            model_name='companysalarydetails',
            name='salaryRule',
        ),
        migrations.RemoveField(
            model_name='companysalaryformat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='companysalaryformatconditional',
            name='salaryFormat',
        ),
        migrations.RemoveField(
            model_name='companyworkshift',
            name='workDay',
        ),
        migrations.RemoveField(
            model_name='companyworkrate',
            name='workshift',
        ),
        migrations.RemoveField(
            model_name='companyworkshiftfreetime',
            name='workshift',
        ),
        migrations.RemoveField(
            model_name='workrecord',
            name='worksheet',
        ),
        migrations.RemoveField(
            model_name='worksalary',
            name='worksheet',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='user',
        ),
        migrations.AlterField(
            model_name='photos',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.album'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tuchamcong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('tencongty', models.CharField(blank=True, max_length=150, null=True)),
                ('ngaybatdau', models.DateField(default=django.utils.timezone.now)),
                ('bophan', models.CharField(blank=True, max_length=150, null=True)),
                ('chucvu', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kieungay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenloaingay', models.CharField(blank=True, max_length=200, null=True)),
                ('ghichu', models.TextField(default=None)),
                ('ngaycuthe', models.TextField(default=None)),
                ('ngaytrongtuan', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.CreateModel(
            name='Kieuca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenca', models.CharField(blank=True, max_length=200, null=True)),
                ('ghichu', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.CreateModel(
            name='Heso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batdau', models.TimeField(default='08:00:00')),
                ('ketthuc', models.TimeField(default='17:00:00')),
                ('heso', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kieuca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kieuca')),
                ('kieungay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kieungay')),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.CreateModel(
            name='Tuchamcongtay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField(default=django.utils.timezone.now)),
                ('giovao', models.DateTimeField(default=app.models.default_giovao)),
                ('giora', models.DateTimeField(default=app.models.default_giora)),
                ('tangca', models.FloatField(default=0)),
                ('vaomuon', models.FloatField(default=0)),
                ('giolam', models.FloatField(default=0)),
                ('dilam', models.BooleanField(default=True)),
                ('nghicoluong', models.BooleanField(default=True)),
                ('nghicochuyencan', models.BooleanField(default=True)),
                ('ghichu', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.CreateModel(
            name='TutinhChuyencan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socongyeucau', models.IntegerField(default=26)),
                ('tienchuyencan', models.FloatField(default=0)),
                ('nghi1ngay', models.FloatField(default=0)),
                ('nghi2ngay', models.FloatField(default=0)),
                ('nghi3ngay', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.CreateModel(
            name='Tutinhluong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenluong', models.CharField(blank=True, max_length=150, null=True)),
                ('tinhvaotangca', models.BooleanField(default=True)),
                ('phaidilamdu', models.BooleanField(default=True)),
                ('socongyeucau', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuchamcong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tuchamcong')),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyDepartment',
        ),
        migrations.DeleteModel(
            name='CompanyEmployee',
        ),
        migrations.DeleteModel(
            name='CompanyPosition',
        ),
        migrations.DeleteModel(
            name='CompanySalaryDetails',
        ),
        migrations.DeleteModel(
            name='CompanySalaryRule',
        ),
        migrations.DeleteModel(
            name='CompanySalaryFormat',
        ),
        migrations.DeleteModel(
            name='CompanySalaryFormatConditional',
        ),
        migrations.DeleteModel(
            name='CompanyWokingday',
        ),
        migrations.DeleteModel(
            name='CompanyWorkrate',
        ),
        migrations.DeleteModel(
            name='CompanyWorkshift',
        ),
        migrations.DeleteModel(
            name='CompanyWorkshiftFreetime',
        ),
        migrations.DeleteModel(
            name='WorkRecord',
        ),
        migrations.DeleteModel(
            name='WorkSalary',
        ),
        migrations.DeleteModel(
            name='WorkSheet',
        ),
    ]
