# Generated by Django 5.0.6 on 2024-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_companysalaryrule_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
