# Generated by Django 5.0.6 on 2024-09-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tutinhluong_luong'),
    ]

    operations = [
        migrations.AddField(
            model_name='kieungay',
            name='cochuyencan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heso',
            name='batdau',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='heso',
            name='ketthuc',
            field=models.TimeField(blank=True, default='17:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='kieuca',
            name='ghichu',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kieungay',
            name='ghichu',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kieungay',
            name='ngaycuthe',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kieungay',
            name='ngaytrongtuan',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
