# Generated by Django 5.0.2 on 2024-09-26 14:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_kieungay_cochuyencan_alter_heso_batdau_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuchamcong',
            name='ngaybatdau',
            field=models.DateField(default=app.models.get_current_date),
        ),
    ]
