# Generated by Django 5.0.2 on 2024-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_tuchamcong_ngaybatdau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuchamcongtay',
            name='dilam',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuchamcongtay',
            name='ghichu',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tuchamcongtay',
            name='nghicochuyencan',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuchamcongtay',
            name='nghicoluong',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
