# Generated by Django 5.0.2 on 2024-09-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_capbac_chiaca_chiangay_batthuong_bathuonghistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangluongtheochucvu',
            name='mucluong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thuongtheochucvu',
            name='mucthuong',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
