# Generated by Django 5.0.2 on 2024-10-07 13:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_nhatro_lat_post_remove_nhatro_long_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soPhong', models.CharField(max_length=10)),
                ('giaPhong', models.FloatField(blank=True, default=0, null=True)),
                ('soNguoiToida', models.IntegerField(default=1)),
                ('mota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nguoitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(blank=True, max_length=200, null=True)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('cccd', models.CharField(blank=True, max_length=12, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichsuTieuThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soDienTieuThu', models.FloatField(blank=True, default=0, null=True)),
                ('soNuocTieuThu', models.FloatField(blank=True, default=0, null=True)),
                ('thang', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoiTro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoitro')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
        migrations.CreateModel(
            name='LichsuThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soTienPhong', models.FloatField(blank=True, default=0, null=True)),
                ('soTienDien', models.FloatField(blank=True, default=0, null=True)),
                ('soTienNuoc', models.FloatField(blank=True, default=0, null=True)),
                ('tongTien', models.FloatField(blank=True, default=0, null=True)),
                ('ngayThanhToan', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoiTro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoitro')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
        migrations.CreateModel(
            name='LichsuNguoitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngayBatdauO', models.DateField(blank=True, null=True)),
                ('ngayKetthucO', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nguoiTro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoitro')),
                ('phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phong')),
            ],
        ),
        migrations.CreateModel(
            name='Tang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soTang', models.IntegerField()),
                ('mota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhaTro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tangs', to='app.nhatro')),
            ],
        ),
        migrations.AddField(
            model_name='phong',
            name='tang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phongs', to='app.tang'),
        ),
    ]
