# Generated by Django 5.0.2 on 2024-10-07 13:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_phong_nguoitro_lichsutieuthu_lichsuthanhtoan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='soTienKhac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='soTienRac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='soTienWifi',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lichsuthanhtoan',
            name='ngayThanhToan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ChiTietThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien', models.FloatField(default=0)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lichsu_thanh_toan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_thanh_toan', to='app.lichsuthanhtoan')),
            ],
        ),
    ]
