# Generated by Django 5.0.6 on 2024-10-08 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_lichsuthanhtoan_ghichu_lichsuthanhtoan_ispaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Danhsachnhanvien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congty', models.CharField(blank=True, max_length=200, null=True)),
                ('manhanvien', models.CharField(blank=True, max_length=200, null=True)),
                ('nguoituyen', models.CharField(blank=True, max_length=200, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DanhsachnhanvienDilam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamcongdi', models.BooleanField(default=True)),
                ('ngaydilam', models.DateField(blank=True, max_length=200, null=True)),
                ('giochamcong', models.DateTimeField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manhanvien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.danhsachnhanvien')),
            ],
        ),
    ]
