# Generated by Django 5.0.6 on 2024-10-08 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_danhsachnhanvien_danhsachnhanviendilam'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhsachCongty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congty', models.CharField(blank=True, max_length=200, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('isBaned', models.BooleanField(blank=True, default=True, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='danhsachnhanviendilam',
            name='chamcongdi',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='DanhsachAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zalo_id', models.CharField(blank=True, max_length=200, null=True)),
                ('isAdmin', models.BooleanField(blank=True, default=True, null=True)),
                ('isStaff', models.BooleanField(blank=True, default=True, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('congty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.danhsachcongty')),
            ],
        ),
        migrations.AlterField(
            model_name='danhsachnhanvien',
            name='congty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.danhsachcongty'),
        ),
    ]
