# Generated by Django 5.0.6 on 2024-10-08 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_danhsachcongty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachnhanvien',
            name='HovaTen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='danhsachnhanviendilam',
            name='giochamcong',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=200, null=True),
        ),
    ]
