# Generated by Django 5.0.2 on 2024-10-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_danhsachnhanvien_hovaten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhsachnhanvien',
            name='manhanvien',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
