# Generated by Django 5.0.2 on 2024-10-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_danhsachnhanvien_manhanvien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bangluongtheochucvu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bathuonghistory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='batthuong',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bophan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='capbac',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chamcong',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chiaca',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chiacatheongay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chiangay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chitiechiacatheongay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chitietthanhtoan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='chucvu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='congty',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='danhsachadmin',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='danhsachcongty',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='danhsachnhanvien',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='danhsachnhanviendilam',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='datemark',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='heso',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='kieuca',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='kieungay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lichsunguoitro',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lichsuthanhtoan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lichsutieuthu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='markconfig',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nguoitro',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nhanvien',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nhatro',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='nhatrothongtin',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='phanloaibatthuong',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='phanloaingay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='phong',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='quydinh',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tailieu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tang',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='thumuc',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='thuongtheochucvu',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tuchamcong',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tuchamcongtay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tutinhchuyencan',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tutinhluong',
            options={'ordering': ['id']},
        ),
    ]
