# Generated by Django 5.0.2 on 2024-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_album_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tang',
            name='soTang',
            field=models.CharField(max_length=10),
        ),
    ]
