# Generated by Django 5.0.2 on 2024-10-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_tang_sotang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tang',
            old_name='soTang',
            new_name='tenTang',
        ),
    ]
