# Generated by Django 5.0.2 on 2024-10-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_sotang_tang_tentang'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='isActive',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
