# Generated by Django 5.0.6 on 2024-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_phong_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsunguoitro',
            name='isOnline',
            field=models.BooleanField(default=True),
        ),
    ]
