# Generated by Django 5.0.2 on 2024-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_lichsunguoitro_isonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatro',
            name='tiendien',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nhatro',
            name='tiennuoc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='nhatro',
            name='tienrac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nhatro',
            name='tenTro',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
