# Generated by Django 5.0.2 on 2024-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_nhatro_tiendien_nhatro_tiennuoc_nhatro_tienrac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatro',
            name='tenTro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
