# Generated by Django 5.0.2 on 2024-10-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoitro',
            name='ngaysinh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nguoitro',
            name='quequan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
