# Generated by Django 5.0.2 on 2024-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_nguoitro_ngaysinh_nguoitro_quequan'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoitro',
            name='tiencoc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
