# Generated by Django 5.0.6 on 2024-10-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_nguoitro_tiencoc_lichsunguoitro_tiencoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatro',
            name='tienphong',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
