# Generated by Django 5.0.6 on 2024-10-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_nhatro_tienphong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsunguoitro',
            name='tiencoc',
        ),
        migrations.AddField(
            model_name='nguoitro',
            name='tamtru',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nguoitro',
            name='tiencoc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
