# Generated by Django 5.0.6 on 2024-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_lichsunguoitro_tiencoc_nguoitro_tamtru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguoitro',
            name='tamtru',
            field=models.BooleanField(default=False),
        ),
    ]
