# Generated by Django 5.0.2 on 2024-10-19 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_nguoitro_tiencoc_lichsunguoitro_tiencoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='NhatroNoiquy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiquy', models.TextField(blank=True, null=True)),
                ('tienphat', models.FloatField(blank=True, default=0, null=True)),
                ('mota', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nhaTro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nhatro')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
