# Generated by Django 5.0.2 on 2024-10-20 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_chitietthanhtoan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietthanhtoan',
            name='nguoiTro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.nguoitro'),
        ),
    ]
