# Generated by Django 5.0.2 on 2024-10-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_lichsuthanhtoan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsuthanhtoan',
            name='ngayKetthuc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
