# Generated by Django 5.0.2 on 2024-10-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_lichsuthanhtoan_ngayketthuc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lichsutieuthu',
            old_name='soDienTieuThu',
            new_name='soDienBatdau',
        ),
        migrations.RenameField(
            model_name='lichsutieuthu',
            old_name='soNuocTieuThu',
            new_name='soDienKetthuc',
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='ngaBatdau',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='ngayKetthuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='soNuocBatdau',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='soNuocKetthuc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='tienDien',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='tienNuoc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='tienPhong',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='tienRac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
