# Generated by Django 5.0.2 on 2024-10-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_phong_sodienbandau_remove_phong_sonuocbandau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsutieuthu',
            name='thang',
            field=models.DateField(blank=True, null=True),
        ),
    ]
