# Generated by Django 5.0.2 on 2024-10-20 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_lichsutieuthu_thang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='nguoiTro',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='soDienBatdau',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='soNuocBatdau',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='tienDien',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='tienNuoc',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='tienPhong',
        ),
        migrations.RemoveField(
            model_name='lichsutieuthu',
            name='tienRac',
        ),
        migrations.AddField(
            model_name='lichsutieuthu',
            name='hoadon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.lichsuthanhtoan'),
        ),
    ]
