# Generated by Django 5.0.2 on 2024-10-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_nhatro_random_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhatro',
            name='random_key',
        ),
    ]
