# Generated by Django 5.0.2 on 2024-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_nhatro_random_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhatro',
            name='random_key',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
