# Generated by Django 5.0.2 on 2024-10-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_nhatro_random_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhatro',
            old_name='random_key',
            new_name='tkey',
        ),
    ]
