# Generated by Django 5.0.2 on 2024-10-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_rename_random_key_nhatro_tkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhatro',
            old_name='tkey',
            new_name='QRKey',
        ),
        migrations.AlterField(
            model_name='nhatro',
            name='isBand',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='nhatro',
            name='isLock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
