# Generated by Django 5.0.6 on 2024-10-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_rename_tkey_nhatro_qrkey_alter_nhatro_isband_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='giaDien',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='giaKhac',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='giaNuoc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='giaRac',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
