# Generated by Django 5.0.6 on 2024-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_phong_giadien_phong_giakhac_phong_gianuoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatro',
            name='tienkhac',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
