# Generated by Django 5.0.6 on 2024-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_nhatro_tienkhac'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichsuthanhtoan',
            name='Key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
