# Generated by Django 5.0.6 on 2024-11-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_chitietthanhtoan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhatro',
            name='ngay_thu_tien',
            field=models.PositiveSmallIntegerField(blank=True, default=15),
        ),
    ]
