# Generated by Django 5.0.6 on 2024-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_nhatro_ngay_thu_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_Chutro',
            field=models.BooleanField(default=False),
        ),
    ]
