# Generated by Django 5.1.3 on 2024-11-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_restaurant_layout_restaurant_space_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_layout",
            name="avatar",
            field=models.TextField(blank=True, null=True),
        ),
    ]
