# Generated by Django 5.1.3 on 2024-11-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_remove_restaurant_layout_avatar_restaurant_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant_space",
            name="is_ordering",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="restaurant_space_group",
            name="is_ordering",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="restaurant_staff",
            name="is_Active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="restaurant_staff",
            name="is_Admin",
            field=models.BooleanField(default=True),
        ),
    ]
