# Generated by Django 5.1.3 on 2024-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_alter_restaurant_space_is_ordering_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="Oder_online",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="Takeaway",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="isChat",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="isRate",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
