# Generated by Django 5.0.6 on 2024-11-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_restaurant_mohinh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_menu_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant_menu')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='group',
            field=models.ManyToManyField(blank=True, to='app.restaurant_menu_groups'),
        ),
        migrations.CreateModel(
            name='Restaurant_menu_marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurant_menu')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='mark',
            field=models.ManyToManyField(blank=True, to='app.restaurant_menu_marks'),
        ),
    ]
