# Generated by Django 5.0.6 on 2024-11-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_restaurant_menu_groups_restaurant_menu_items_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
