# Generated by Django 5.0.6 on 2024-11-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_restaurant_menu_items_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant_menu_items',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
