# Generated by Django 5.0.6 on 2024-11-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_alter_restaurant_menu_items_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='image64_sub1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='image64_sub2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='image64_sub3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
