# Generated by Django 5.0.6 on 2024-11-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_restaurant_menu_items_image64_sub1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_menu_items',
            name='name',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
