# Generated by Django 5.0.6 on 2024-11-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_alter_restaurant_menu_items_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
