# Generated by Django 5.0.6 on 2024-11-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0084_restaurant_menu_items_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='is_ship',
            field=models.BooleanField(default=True),
        ),
    ]
