# Generated by Django 5.0.6 on 2024-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_restaurant_menu_items_is_ship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
