# Generated by Django 5.0.6 on 2024-11-19 04:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_userlikelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='socket_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_address',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_lat',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_long',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_notes',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_phone',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='restaurant_order',
            name='custom_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurant_order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant_order',
            name='is_paided',
            field=models.BooleanField(default=False),
        ),
    ]
