# Generated by Django 5.1.3 on 2024-11-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_alter_restaurant_order_custom_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_order",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.restaurant_space_group",
            ),
        ),
        migrations.AddField(
            model_name="restaurant_order",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.restaurant_space",
            ),
        ),
    ]
