# Generated by Django 5.0.6 on 2024-11-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_restaurant_order_group_restaurant_order_space'),
        ('app', '0095_restaurant_wallpaper'),
    ]

    operations = [
    ]
