# Generated by Django 5.0.6 on 2024-11-21 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_restaurant_menu_items_is_validate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Đã tạo'), ('RECEIVED', 'Đã nhận'), ('SHIPPING', 'Đang ship'), ('DELIVERED', 'Đã giao'), ('PADING', 'Đang thanh toán'), ('COMPLETE', 'Hoàn thành'), ('NOT', 'Không nhận'), ('CANCEL', 'Người dùng hủy')], default='CREATED', max_length=10),
        ),
        migrations.AlterField(
            model_name='restaurant_order_items',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app.restaurant_order'),
        ),
    ]
