# Generated by Django 5.0.6 on 2024-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_restaurant_order_cancel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Đã tạo'), ('RECEIVED', 'Đã nhận'), ('SHIPPING', 'Đang ship'), ('DELIVERED', 'Đã giao'), ('PAIDING', 'Đang thanh toán'), ('COMPLETE', 'Hoàn thành'), ('NOT', 'Không nhận'), ('CANCEL', 'Người dùng hủy')], default='CREATED', max_length=20),
        ),
    ]
