# Generated by Django 5.1.3 on 2024-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_alter_restaurant_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_space",
            name="is_inuse",
            field=models.BooleanField(default=True),
        ),
    ]
