# Generated by Django 5.1.3 on 2024-11-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0102_restaurant_space_user_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_order_items",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAIT", "Chưa giao"),
                    ("DONE", "Đã giao"),
                    ("CANCEL", "Hết hàng"),
                ],
                default="WAIT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant_order",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurant_order_set",
                to="app.restaurant",
            ),
        ),
    ]
