# Generated by Django 5.1.3 on 2024-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0103_restaurant_order_items_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant_order",
            name="is_clear",
            field=models.BooleanField(default=False),
        ),
    ]
