# Generated by Django 5.0.6 on 2024-11-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_restaurant_order_is_clear'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_menu_items',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
