# Generated by Django 5.1.3 on 2024-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0105_restaurant_menu_items_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="bankCode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="bankValue",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
