# Generated by Django 5.1.3 on 2024-11-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0106_restaurant_bankcode_restaurant_bankvalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="bankName",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
