# Generated by Django 5.1.3 on 2024-11-26 08:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0108_danhsachnhanvien_calamviec"),
    ]

    operations = [
        migrations.CreateModel(
            name="DanhsachNhanvien_record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manhanvien",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("HovaTen", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "calamviec",
                    models.CharField(
                        choices=[
                            ("cangay", "cangay"),
                            ("cadem", "cadem"),
                            ("ca1", "ca1"),
                            ("ca2", "ca2"),
                            ("ca3", "ca3"),
                            ("hanhchinh", "hanhchinh"),
                            ("khac", "khac"),
                        ],
                        default="cangay",
                        max_length=50,
                    ),
                ),
                ("nguoituyen", models.CharField(blank=True, max_length=200, null=True)),
                ("ghichu", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.danhsachcongty",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
