# Generated by Django 5.1.3 on 2024-11-26 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0109_danhsachnhanvien_record"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="danhsachnhanvien_record",
            old_name="HovaTen",
            new_name="column",
        ),
        migrations.RenameField(
            model_name="danhsachnhanvien_record",
            old_name="nguoituyen",
            new_name="new_value",
        ),
        migrations.RemoveField(
            model_name="danhsachnhanvien_record",
            name="calamviec",
        ),
        migrations.RemoveField(
            model_name="danhsachnhanvien_record",
            name="congty",
        ),
        migrations.RemoveField(
            model_name="danhsachnhanvien_record",
            name="manhanvien",
        ),
        migrations.AddField(
            model_name="danhsachnhanvien",
            name="nghiviec",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="danhsachnhanvien_record",
            name="ngayapdung",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="danhsachnhanvien_record",
            name="nhanvien",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.danhsachnhanvien",
            ),
        ),
        migrations.AddField(
            model_name="danhsachnhanvien_record",
            name="old_value",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="danhsachnhanvien_record",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
