# Generated by Django 5.0.6 on 2024-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_rename_hovaten_danhsachnhanvien_record_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_order_items',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
