# Generated by Django 5.0.6 on 2024-11-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_restaurant_order_items_is_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_order_items',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
