# Generated by Django 5.1.3 on 2024-12-22 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0114_zalo_hook"),
    ]

    operations = [
        migrations.CreateModel(
            name="NhanvienSorting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("socccd", models.CharField(blank=True, max_length=200, null=True)),
                ("hovaten", models.CharField(blank=True, max_length=200, null=True)),
                ("ngaysinh", models.DateField(blank=True, null=True)),
                ("ngayvao", models.DateField(blank=True, null=True)),
                ("sdt", models.CharField(blank=True, max_length=200, null=True)),
                ("biensoxe", models.CharField(blank=True, max_length=200, null=True)),
                ("quequan", models.CharField(blank=True, max_length=200, null=True)),
                ("gioitinh", models.CharField(blank=True, max_length=200, null=True)),
                ("anhchup", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
