# Generated by Django 5.1.3 on 2024-12-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0116_danhsachnhanvien_record_isdilam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="danhsachnhanvien_record",
            name="isDilam",
        ),
        migrations.AddField(
            model_name="nhanviensorting",
            name="isDilam",
            field=models.BooleanField(default=True),
        ),
    ]
