"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os, environ
from pathlib import Path
from corsheaders.defaults import default_headers

# Initialize environment variables
env = environ.Env()
# Read .env file
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='S#perS3crEt_007')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'attendance',
    'app',
    'quan_ly_nhan_luc',
    'oauth2_provider',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
}
OAUTH2_PROVIDER_URL = 'http://localhost:5005'
# Cấu hình OAuth2
OAUTH2_CLIENT_ID = env('OAUTH2_CLIENT_ID')
OAUTH2_CLIENT_SECRET = env('OAUTH2_CLIENT_SECRET')
OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 360000,
    'REFRESH_TOKEN_EXPIRE_SECONDS': 1209600,
    'SCOPES': {
        'read': 'Read access',
        'write': 'Write access',
    }
}
CORS_ALLOWED_ORIGINS = [
    'https://order.lenmon.cloud',
    'https://lenmon.cloud',
    'https://ipays.vn',
    'http://localhost:3001',
    'http://localhost:3003',
    'http://localhost:3009',
    'http://localhost:3000',
    "http://localhost:4000",
    "http://localhost:6500",
    "http://localhost:8008",
    "http://localhost:8000",
    "http://localhost:8080",
    "http://192.168.110.120",
    "http://192.168.1.23:6500",
    'https://hoanglongdjc.cloud',
    'https://h5.zdn.vn',
    'zbrowser://h5.zdn.vn',
    'https://h5.zadn.vn',
    'zbrowser://h5.zadn.vn',
]
ALLOWED_HOSTS = [
    'ipays.vn',
    'https://ipays.vn',
    'https://order.lenmon.cloud',
    'https://lenmon.cloud',
    'https://hoanglongdjc.cloud',
    'www.order.lenmon.cloud',
    'www.lenmon.cloud',
    'www.hoanglongdjc.cloud',
    'www.ipays.vn',
    'localhost',
    'localhost:6500',
    'localhost:8008',
    'localhost:8000',
    'localhost:8080',
    'localhost:3001',
    'localhost:3003',
    'localhost:3000',
    'localhost:4000',
    'localhost:3009',
    '192.168.110.120',
    '192.168.1.23',
    '192.168.110.120:5005',
    'https://h5.zdn.vn',
    'zbrowser://h5.zdn.vn',
    'https://h5.zadn.vn',
    'zbrowser://h5.zadn.vn',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
    'HEAD',
]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    # các middleware khác
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_HEADERS = list(default_headers) + [
    'ApplicationKey',
    'Companykey',
]
ROOT_URLCONF = 'core.urls'
AUTHENTICATION_BACKENDS = [
    'app.authentication.ZaloBackend',
    'django.contrib.auth.backends.ModelBackend',  # Cho phép đăng nhập bằng username như bình thường
]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

DATA_UPLOAD_MAX_NUMBER_FIELDS = 500000

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Thay đổi thành múi giờ bạn muốn
USE_TZ = True  # Bật tính năng timezone (mặc định là True)