# Generated by Django 5.0.6 on 2025-01-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Company Accounts', 'verbose_name_plural': 'Company Accounts'},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'username')},
        ),
    ]
