# Generated by Django 5.0.6 on 2025-01-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Punchtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(blank=True, null=True)),
                ('att_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_time',
            field=models.ManyToManyField(to='attendance.punchtime'),
        ),
    ]
