# Generated by Django 5.0.6 on 2025-01-20 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_week_attendance_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_check', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('request', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.CharField(blank=True, max_length=200, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendance')),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_imp_user', to='attendance.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_req_user', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_check', models.BooleanField(default=False)),
                ('is_close', models.BooleanField(default=False)),
                ('is_accept', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('response', models.TextField(blank=True, max_length=200, null=True)),
                ('implement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_imp_user', to='attendance.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_req_user', to='attendance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TimeField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('deparment', models.CharField(blank=True, max_length=200, null=True)),
                ('zalo_id', models.CharField(blank=True, max_length=200, null=True)),
                ('zalo_number', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.employee')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
