# Generated by Django 5.0.6 on 2025-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='startday',
            field=models.IntegerField(default=1),
        ),
    ]
