# Generated by Django 5.0.6 on 2025-01-21 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_profile_join_date_profile_leave_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
        migrations.AlterField(
            model_name='punchtime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.employee'),
        ),
    ]
