# Generated by Django 5.0.6 on 2025-01-21 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_emp_id_alter_attendance_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='attendanceticket',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='attendanceticketcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='employeemessage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='employeemessagecomment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='punchtime',
            options={'ordering': ['-id']},
        ),
    ]
