# Generated by Django 5.0.6 on 2025-01-21 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
