# Generated by Django 5.0.6 on 2025-01-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_punchtime_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
