# Generated by Django 5.0.6 on 2025-01-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-att_date']},
        ),
    ]
